# Generated by Django 3.2.21 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_table',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='driver_table',
            name='place',
        ),
    ]
