# Generated by Django 5.1.3 on 2025-03-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_auto_20240203_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_table',
            name='regno',
            field=models.CharField(max_length=50),
        ),
    ]
