# Generated by Django 5.1.3 on 2025-03-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0003_alter_driver_table_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency_number',
            name='relation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
