# Generated by Django 5.1.6 on 2025-04-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0004_emergency_number_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficpoolice_table',
            name='latitude',
            field=models.CharField(default=11.56, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficpoolice_table',
            name='longitude',
            field=models.CharField(default='10:00:00', max_length=100),
            preserve_default=False,
        ),
    ]
